  
version: '3.8'
services:
  postgres:
    image: postgres:11.7-alpine
    restart: always
    environment:
      - POSTGRES_USER=abdel
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=vuejsprisma_dev
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  nodejs-server:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    depends_on:
      - postgres
    ports:
      - "3080:3080"
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  vue-ui:
    build:
      context: ./my-app
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    volumes:
       - ./my-app:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules
volumes:
  postgres: